<?php
/** @var \Loyalty\Point\Block\Customer\HistoryLoyaltyPoint $block */
$history = $block->getPointHistory();
$count = count($history);
?>
<div class="point-balance">
    <p style="padding-bottom: 20px; border-bottom:1px solid #d1d1d1;">
        <b>Point Balance:</b> <?= $block->getPointBalance() ?>
    </p>
</div>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?= __('Orders') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?= __('Id') ?></th>
            <th scope="col" class="col date"><?= __('Points') ?></th>
            <th scope="col" class="col shipping"><?= __('Resource') ?></th>
            <th scope="col" class="col total"><?= __('Date') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php for ($i = $count-1; $i >= max($count - 19, 0); $i--): ?>
            <tr>
                <td class="col id"><?= $history[$i]['history_id'] ?></td>
                <td class="col id"><?= $history[$i]['points'] ?></td>
                <td class="col id"><?= $history[$i]['source'] ?></td>
                <td class="col id"><?= $history[$i]['created_at'] ?></td>
            </tr>
        <?php endfor; ?>
        </tbody>
    </table>
</div>

